### ISSUE TITLE
Covalent to ionic bond

### ISSUE THREAD

**Issue by sonial** [chembl/ChEMBL_Structure_Pipeline#30]
Hi,

Thanks for developing this pipeline and making it available, it is really useful!

I noticed that the standardizer fixes covalent bonds to ionic in alkaline oxides, and it might be worth extending this to alkaline-earth oxides and metal halides.

See the example below for calcium chloride with covalent bonds (wrong SMILES created on purpose), as well as the ChEMBL entry for [Calcium oxide](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2104397/) erroneously represented with a covalent double bond. 

```
from chembl_structure_pipeline import standardizer
from rdkit import Chem

smiles = "[Ca](Cl)Cl"
mol = Chem.MolFromSmiles(smiles)
mol
```
![image](https://user-images.githubusercontent.com/7021751/137355133-cb873a81-da0d-4cb5-a9ae-3e8d650301e5.png)

```
mol_stand = standardizer.standardize_molblock(Chem.MolToMolBlock(mol))
Chem.MolFromMolBlock(mol_stand)
```
![image](https://user-images.githubusercontent.com/7021751/137355505-6487a628-df30-4031-83e6-b907cebf9135.png)

Cheers,
Sonia

**Comment by BZdrazil** [comment]
Hi Sonia,

Thanks for your comment regarding covalent to ionic bond issues within ChEMBL. 

Currently, the smirks rule for  fixing covalent bonds to ionic in alkaline oxides is not working in our pipeline and it will require more time to implement this.

When looking at specific compounds that contain calcium there are a few compounds where calcium is drawn with covalent bonds instead of ionic (for instance your example of calcium oxide). These issues will be fixed manually but might take a while before these corrections are visible on the ChEMBL interface. 

With regards to the metal halides. In ChEMBL we don’t show structures for the majority of metals (see full list: https://github.com/chembl/ChEMBL_Structure_Pipeline/blob/master/chembl_structure_pipeline/exclude_flag.py#L13). Zinc and silver are, however, not in this list of metals for flagging compounds to be excluded from curation since these are more frequently occurring metals (mostly they are building the counterion for salt formation). We had a look at the compounds in ChEMBL that contain zinc and silver and it shows a few discrepancies regarding silver compounds. These issues will also be manually fixed as well and like with the calcium corrections it will take a while before they are visible on the interface.

In ChEMBL we tend to correct most inaccuracies found in the database manually. The errors usually include a small number of compounds and hence this is a less time-consuming option then adding corrections to the pipeline at the moment.

Best regards,

The ChEMBL Team
